// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_projekat.Models;

namespace WEB_projekat.Migrations
{
    [DbContext(typeof(FrizerskiSalonContext))]
    [Migration("20210817203049_v3")]
    partial class v3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WEB_projekat.Models.Raspored", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("M")
                        .HasColumnType("int")
                        .HasColumnName("M");

                    b.Property<int>("MaxKapacitet")
                        .HasColumnType("int")
                        .HasColumnName("MaxKapacitet");

                    b.Property<int>("N")
                        .HasColumnType("int")
                        .HasColumnName("N");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.ToTable("Raspored");
                });

            modelBuilder.Entity("WEB_projekat.Models.Termin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ime");

                    b.Property<int>("M")
                        .HasColumnType("int")
                        .HasColumnName("M");

                    b.Property<int>("MaxKapacitet")
                        .HasColumnType("int")
                        .HasColumnName("Kapacitet");

                    b.Property<int>("N")
                        .HasColumnType("int")
                        .HasColumnName("N");

                    b.Property<int?>("RasporedID")
                        .HasColumnType("int");

                    b.Property<bool>("Rezervisan")
                        .HasColumnType("bit")
                        .HasColumnName("Rezervisan");

                    b.Property<string>("Usluga")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Usluga");

                    b.HasKey("ID");

                    b.HasIndex("RasporedID");

                    b.ToTable("Termin");
                });

            modelBuilder.Entity("WEB_projekat.Models.Tretman", b =>
                {
                    b.Property<int>("RedniBroj")
                        .HasColumnType("int")
                        .HasColumnName("RedniBroj");

                    b.Property<int>("Cena")
                        .HasColumnType("int")
                        .HasColumnName("Cena");

                    b.Property<int?>("TerminID")
                        .HasColumnType("int");

                    b.Property<int>("VremeTrajanja")
                        .HasColumnType("int")
                        .HasColumnName("VremeTrajanja");

                    b.HasKey("RedniBroj");

                    b.HasIndex("TerminID");

                    b.ToTable("Tretman");
                });

            modelBuilder.Entity("WEB_projekat.Models.Termin", b =>
                {
                    b.HasOne("WEB_projekat.Models.Raspored", "Raspored")
                        .WithMany("Termini")
                        .HasForeignKey("RasporedID");

                    b.Navigation("Raspored");
                });

            modelBuilder.Entity("WEB_projekat.Models.Tretman", b =>
                {
                    b.HasOne("WEB_projekat.Models.Termin", "Termin")
                        .WithMany("Tretmani")
                        .HasForeignKey("TerminID");

                    b.Navigation("Termin");
                });

            modelBuilder.Entity("WEB_projekat.Models.Raspored", b =>
                {
                    b.Navigation("Termini");
                });

            modelBuilder.Entity("WEB_projekat.Models.Termin", b =>
                {
                    b.Navigation("Tretmani");
                });
#pragma warning restore 612, 618
        }
    }
}
